Do we need pycairo?

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -21,7 +21,7 @@ jobs:
         uses: astral-sh/setup-uv@v3
 
       - name: Install system level packages
-        run: (sudo apt-get update || echo "sometimes this fails because of the azure cli repo which we do not use") && sudo apt-get install -y libcairo2-dev libgirepository1.0-dev pkg-config python3-dev && sudo apt-get clean
+        run: (sudo apt-get update || echo "sometimes this fails because of the azure cli repo which we do not use") && sudo apt-get install -y  libgirepository1.0-dev pkg-config python3-dev && sudo apt-get clean
 
       - name: Install dependencies
         run: uv tool install tox --with tox-uv
@@ -54,7 +54,7 @@ jobs:
           python-version: '3.11'
           
       - name: Install system level packages
-        run: (sudo apt-get update || echo "sometimes this fails because of the azure cli repo which we do not use") && sudo apt-get install -y libcairo2-dev libgirepository1.0-dev pkg-config python3-dev && sudo apt-get clean
+        run: (sudo apt-get update || echo "sometimes this fails because of the azure cli repo which we do not use") && sudo apt-get install -y  libgirepository1.0-dev pkg-config python3-dev && sudo apt-get clean
 
       - name: Install tox
         run: uv tool install tox --with tox-uv
@@ -107,7 +107,7 @@ jobs:
           restore-keys: npm-
 
       - name: Install system level packages
-        run: sudo apt-get update && sudo apt-get install -y tesseract-ocr texlive libcairo2-dev libgirepository1.0-dev pkg-config python3-dev && sudo apt-get clean
+        run: sudo apt-get update && sudo apt-get install -y tesseract-ocr texlive  libgirepository1.0-dev pkg-config python3-dev && sudo apt-get clean
 
       - uses: actions/setup-python@v5
         with:
@@ -177,7 +177,7 @@ jobs:
           restore-keys: npm-
 
       - name: Install system level packages
-        run: sudo apt-get update && sudo apt-get install -y tesseract-ocr texlive libcairo2-dev libgirepository1.0-dev pkg-config python3-dev && sudo apt-get clean
+        run: sudo apt-get update && sudo apt-get install -y tesseract-ocr texlive  libgirepository1.0-dev pkg-config python3-dev && sudo apt-get clean
 
       - uses: actions/setup-python@v5
         with:
@@ -242,7 +242,7 @@ jobs:
           restore-keys: npm-
 
       - name: Install system level packages
-        run: sudo apt-get update && sudo apt-get install -y tesseract-ocr texlive libcairo2-dev libgirepository1.0-dev pkg-config python3-dev && sudo apt-get clean
+        run: sudo apt-get update && sudo apt-get install -y tesseract-ocr texlive  libgirepository1.0-dev pkg-config python3-dev && sudo apt-get clean
 
       - uses: actions/setup-python@v5
         with:
@@ -386,7 +386,7 @@ jobs:
           restore-keys: npm-
 
       - name: Install system level packages
-        run: sudo apt-get update && sudo apt-get install -y tesseract-ocr texlive libcairo2-dev libgirepository1.0-dev pkg-config python3-dev && sudo apt-get clean
+        run: sudo apt-get update && sudo apt-get install -y tesseract-ocr texlive  libgirepository1.0-dev pkg-config python3-dev && sudo apt-get clean
 
       - uses: actions/setup-python@v5
         with:
