Ignore failed updates during CI because we don't care for the azure CLI which is currently borked

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -51,7 +51,7 @@ jobs:
           python-version: '3.10'
           
       - name: Install system level packages
-        run: sudo apt-get update && sudo apt-get install -y libcairo2-dev libgirepository1.0-dev pkg-config python3-dev && sudo apt-get clean
+        run: (sudo apt-get update || echo "sometimes this fails because of the azure cli repo which we do not use") && sudo apt-get install -y libcairo2-dev libgirepository1.0-dev pkg-config python3-dev && sudo apt-get clean
 
       - name: Install tox
         run: uv tool install tox --with tox-uv
